# Default values for the Helm Chart

fullnameOverride:
nameOverride:
gitSecretName: tekton-git

config:
  # gs://BUCKET_NAME/jenkins-x/logs/{{.Owner}}/{{.Repository}}/{{if hasPrefix .Branch \"pr\"}}{{.Branch | upper}}{{else}}{{.Branch}}{{end}}/{{.Build}}.log
  archivedLogsURLTemplate:
  namespace: jx
  resyncInterval: 60s
  logLevel: INFO

image:
  repository: gcr.io/jenkinsxio/jx-pipelines-visualizer
  # If no tag, fallback to the Chart's AppVersion
  tag:
  pullPolicy:

deployment:
  replicas: 1
  revisionHistoryLimit: 2
  labels: {}
  annotations: {}

pod:
  resources:
    requests:
      cpu: "0.2"
      memory: 128M
    limits:
      cpu: "1"
      memory: 512M
  labels: {}
  annotations: {}
  activeDeadlineSeconds:
  enableServiceLinks: false
  terminationGracePeriodSeconds:
  affinity: {}
  nodeSelector: {}
  tolerations: []
  hostAliases: []
  schedulerName:
  securityContext:
    fsGroup: 1000
  env: {}

service:
  port: 80
  type:
  loadBalancerIP:
  labels: {}
  annotations: {}

ingress:
  enabled: false
  labels: {}
  annotations: {}

  # hosts:
  # - pipelines.example.com
  # - pipelines.foo.bar
  hosts: []


  # enables basic auth secret to be created
  basicAuth:
    enabled: false
    authData: ""

  tls:
    enabled: false

    # secrets:
    #   embedded:
    #     b64encodedCertificate: e30k
    #     b64encodedCertificateKey: e30k
    #     hosts:
    #     - pipelines.example.com
    #   existing-secret-name: {}
    #   existing-secret-name-with-custom-hosts:
    #     hosts:
    #     - pipelines.foo.bar 
    secrets: {}

istio:
  enabled: false
  apiVersion: networking.istio.io/v1beta1
  gateway: jx-gateway

serviceAccount:
  # allow additional annotations to be added to the ServiceAccount
  # such as for workload identity on clouds
  annotations: {}

role:
  rules:
  - apiGroups:
    - jenkins.io
    resources:
    - pipelineactivities
    - pipelinestructures
    verbs:
    - list
    - watch
    - get
  - apiGroups:
    - tekton.dev
    resources:
    - pipelineruns
    verbs:
    - list
    - watch
    - get
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
    - watch
    - get
  - apiGroups:
    - ""
    resources:
    - pods/log
    verbs:
    - get